---
title: "STA457  Final project"
author: '"Yukun Gao"'
date: "2022/3/28"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## (a)
First, we plot the data

```{r}
#load the data
library(forecast)
library(ggplot2)
library(astsa); data(unemp)
x = unemp
lx = log(x); dlx = diff(lx); ddlx = diff(dlx, 12)

plot.ts(x, xlab = "Time", col="blue",ylab = "Unemployment in 10,000 of Persons",
main = "Monthly U.S. Unemployment")

```

Plot after log, diff, and seasonal diff

```{r}
par(mfrow=c(2,1) ,mar=c(3.8,4,1.5,1.5),font.axis=1,font.lab=2,cex.lab=0.7,cex.axis=0.6)

plot.ts(dlx,main = "First Difference on Logged Data",col = "blue",ylab = "Unemployment")
plot.ts(ddlx,main = "Twelfth Difference on Differenced Logged Data",col = "blue",ylab = "Unemployment")
```
 and the ACF and PACF:

```{r}
monthplot(ddlx)
plot1<- acf2(ddlx, max.lag = 100 , main="ACF and PACF of Transformed U.S. Unemployment Series",cex.main=1)
```



```{r}
##ddlx
#good
model1<- sarima(lx ,3,1,0,0,1,1, 12 )
print(model1$ttable)

#very good
model2<- sarima(lx ,3,1,2,0,1,1, 12 )
print(model2$ttable)
```


```{r}
data.frame( AIC= c(model1$AIC,model2$AIC), AICc=c(model1$AICc,model2$AICc), BIC= c(model1$BIC,model2$BIC))
```

$$
y_t=\nabla_{12}\nabla\log(x_t)=(1-B^{12})(1-B)log(x_t)=log(x_t)-log(x_{t-1})-log(x_{t-12})+log(x_{t-13})
$$
$$
(1-\phi_1B-\phi_2B^2-\phi_3B^3)y_t =(1+\theta_1B+\theta_2B^2)(1+\Theta_1B^{12})w_t
\\
\Longleftrightarrow\\
(1-1.6588B+0.5285B^2+0.1488B^3)\hat{y_t}= (1-1.6505B+0.6505B^2)(1-0.6811B^{12})\hat{w_t} \\
\Longleftrightarrow\\
\hat{y_t}=1.6588\hat{y_{t-1}}-0.5285\hat{y_{t-2}}-0.1488\hat{y_{t-3}}+\hat{w_t}-1.6505\hat{w_{t-1}}\\+0.6505\hat{w_{t-2}}-0.6811\hat{w_{t-12}}+1.1242\hat{w_{t-13}}-0.443\hat{w_{t-14}}
$$


```{r}
Logged_Unemployment=lx
predict.unemp <- sarima.for(Logged_Unemployment, main="Forecasting of Logged U.S. Unemployment Level", 10, 3,1,2, 0,1,1,12,cex.main=1)
```

little increasing trend


```{r}
#upper <-exp(predict.unemp$pred)+qnorm(0.975)*exp(predict.unemp$se)
#lower <-exp(predict.unemp$pred)-qnorm(0.975)*exp(predict.unemp$se)
#round(exp(predict.unemp$pred),3)
#round(upper,3)
#round(lower,3)
upper = predict.unemp$pred+qnorm(0.975)*predict.unemp$se
# lower bound
lower = predict.unemp$pred-qnorm(0.975)*predict.unemp$se
# Construct a data frame
(data.frame("Prediction"=round(predict.unemp$pred,3) ,"PI 95% Lower Bound"=round(lower,3),"PI 95% Upper Bound"=round(upper,3)))
```
## spectral 
```{r}
unemp_per <- mvspec(lx, log="no")
#unemp_per1 <- mvspec(x, log="yes")
```

```{r}
freq <- unemp_per$details[order(unemp_per$details[,3], decreasing = TRUE),]
freq[1,]
freq[2,]
freq[3,]
```

```{r}
#95% CI of the dominant frequencies
library(MASS)
unemp_up1 <- 2*freq[1,3]/qchisq(.025,2)
unemp_lo1 <- 2*freq[1,3]/qchisq(.975,2)
unemp_up2 <- 2*freq[2,3]/qchisq(.025,2)
unemp_lo2 <- 2*freq[2,3]/qchisq(.975,2)
unemp_up3 <- 2*freq[3,3]/qchisq(.025,2)
unemp_lo3 <- 2*freq[3,3]/qchisq(.975,2)
#Create dataframe
df <- data.frame(series=c(rep("Unemployment", 3)), Dom_Frequency=c(freq[1,1], freq[2,1],freq[3,1]), spec=c(freq[1,3], freq[2,3], freq[3,3]), Lower.CI=c(unemp_lo1, unemp_lo2, unemp_lo3), Upper.CI=c(unemp_up1, unemp_up2, unemp_up3))
df[2:5]=round(df[2:5], 4)
df
```


